X_TEAINE_SERVICE = "X-Teaine-Service"
X_TEAINTE_SERVICE = X_TEAINE_SERVICE
X_TEAINE_API_KEY = "X-Teaine-Api-Key"
X_TEAINE_COMMON_VERSION = "X-Teaine-Common-Version"

__all__ = [
    "X_TEAINE_API_KEY",
    "X_TEAINE_COMMON_VERSION",
    "X_TEAINE_SERVICE",
    "X_TEAINTE_SERVICE",
]
