[project]
name = "teaine-archer"
version = "0.1.0"
description = "The platform event collector and adapter of Project Teaine."
authors = [
    { name = "Nranphy", email = "Nranphy@outlook.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.2,<0.8.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "teaine-common",
    "websockets>=16.0",
]

[tool.uv.sources]
teaine-common = { path = "../teaine-common", editable = true }
