version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.13
    volumes:
      - ..:/workspaces/Teaine-Project:cached
    environment:
      PYTHONUNBUFFERED: 1
    command: sleep infinity
