[project]
name = "teaine-ruler"
version = "0.1.0"
description = "The resource manager backend of Project Teaine."
authors = [
    { name = "Nranphy", email = "Nranphy@outlook.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "asyncpg>=0.31.0",
    "cryptography>=49.0.0",
    "fastapi[standard]>=0.139.2",
    "loguru>=0.7.3",
    "pydantic-settings>=2.14.2",
    "sqlalchemy[asyncio]>=2.0.51",
    "teaine-common",
    "uvicorn[standard]>=0.51.0",
]

[tool.uv.sources]
teaine-common = { path = "../teaine-common", editable = true }

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "httpx2>=2.9.1",
]
